// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Canvas() {
  return window['go']['main']['App']['Canvas']();
}

export function CreateConversation(arg1) {
  return window['go']['main']['App']['CreateConversation'](arg1);
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function DeleteCanvasNode(arg1) {
  return window['go']['main']['App']['DeleteCanvasNode'](arg1);
}

export function EnsureDaemon() {
  return window['go']['main']['App']['EnsureDaemon']();
}

export function FileDiff(arg1, arg2) {
  return window['go']['main']['App']['FileDiff'](arg1, arg2);
}

export function LinkNodes(arg1, arg2) {
  return window['go']['main']['App']['LinkNodes'](arg1, arg2);
}

export function PairNodes(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PairNodes'](arg1, arg2, arg3, arg4);
}

export function PatchCanvasNode(arg1) {
  return window['go']['main']['App']['PatchCanvasNode'](arg1);
}

export function PickProjectDirectory(arg1) {
  return window['go']['main']['App']['PickProjectDirectory'](arg1);
}

export function ProjectChanges(arg1) {
  return window['go']['main']['App']['ProjectChanges'](arg1);
}

export function SendTurn(arg1, arg2) {
  return window['go']['main']['App']['SendTurn'](arg1, arg2);
}

export function SetLoop(arg1, arg2) {
  return window['go']['main']['App']['SetLoop'](arg1, arg2);
}

export function SetLoopRunning(arg1, arg2) {
  return window['go']['main']['App']['SetLoopRunning'](arg1, arg2);
}

export function SetProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProject'](arg1, arg2, arg3);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}

export function UnlinkNodes(arg1) {
  return window['go']['main']['App']['UnlinkNodes'](arg1);
}

export function UpdateLink(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateLink'](arg1, arg2, arg3, arg4);
}
