// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {vcs} from '../models';

export function Canvas():Promise<domain.Canvas>;

export function CreateConversation(arg1:domain.NewConversation):Promise<domain.Conversation>;

export function CreateNote(arg1:domain.NewNote):Promise<domain.CanvasNode>;

export function DeleteCanvasNode(arg1:number):Promise<void>;

export function EnsureDaemon():Promise<void>;

export function FileDiff(arg1:number,arg2:string):Promise<vcs.Diff>;

export function LinkNodes(arg1:number,arg2:number):Promise<domain.CanvasLink>;

export function PairNodes(arg1:number,arg2:number,arg3:string,arg4:number,arg5:string):Promise<Array<domain.CanvasLink>>;

export function PatchCanvasNode(arg1:domain.CanvasNodePatch):Promise<void>;

export function PickProjectDirectory(arg1:string):Promise<string>;

export function ProjectChanges(arg1:number):Promise<vcs.Status>;

export function ResumeDialogue(arg1:number):Promise<void>;

export function SendTurn(arg1:number,arg2:string):Promise<void>;

export function SetLoop(arg1:number,arg2:domain.LoopConfig):Promise<void>;

export function SetLoopRunning(arg1:number,arg2:boolean):Promise<void>;

export function SetProject(arg1:number,arg2:string,arg3:string):Promise<void>;

export function SetRole(arg1:number,arg2:string):Promise<void>;

export function Snapshot():Promise<domain.Snapshot>;

export function UnlinkNodes(arg1:number):Promise<void>;

export function UpdateLink(arg1:number,arg2:string,arg3:number,arg4:boolean,arg5:string):Promise<void>;
