// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Canvas():Promise<domain.Canvas>;

export function CreateConversation(arg1:domain.NewConversation):Promise<domain.Conversation>;

export function CreateNote(arg1:domain.NewNote):Promise<domain.CanvasNode>;

export function DeleteCanvasNode(arg1:number):Promise<void>;

export function EnsureDaemon():Promise<void>;

export function LinkNodes(arg1:number,arg2:number):Promise<domain.CanvasLink>;

export function PatchCanvasNode(arg1:domain.CanvasNodePatch):Promise<void>;

export function SendTurn(arg1:number,arg2:string):Promise<void>;

export function Snapshot():Promise<domain.Snapshot>;

export function UnlinkNodes(arg1:number):Promise<void>;
