// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnsureDaemon() {
  return window['go']['main']['App']['EnsureDaemon']();
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}
