// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function Branch(arg1, arg2, arg3) {
  return window['go']['main']['App']['Branch'](arg1, arg2, arg3);
}

export function CancelConversation(arg1) {
  return window['go']['main']['App']['CancelConversation'](arg1);
}

export function Canvas() {
  return window['go']['main']['App']['Canvas']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CreateConversation(arg1) {
  return window['go']['main']['App']['CreateConversation'](arg1);
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function CreatePipeline(arg1) {
  return window['go']['main']['App']['CreatePipeline'](arg1);
}

export function DeleteCanvasNode(arg1) {
  return window['go']['main']['App']['DeleteCanvasNode'](arg1);
}

export function EnsureDaemon() {
  return window['go']['main']['App']['EnsureDaemon']();
}

export function ExportBoard() {
  return window['go']['main']['App']['ExportBoard']();
}

export function ExportConversation(arg1, arg2) {
  return window['go']['main']['App']['ExportConversation'](arg1, arg2);
}

export function FileDiff(arg1, arg2) {
  return window['go']['main']['App']['FileDiff'](arg1, arg2);
}

export function ImportBoard() {
  return window['go']['main']['App']['ImportBoard']();
}

export function LinkNodes(arg1, arg2) {
  return window['go']['main']['App']['LinkNodes'](arg1, arg2);
}

export function OpenReleasePage(arg1) {
  return window['go']['main']['App']['OpenReleasePage'](arg1);
}

export function PairNodes(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PairNodes'](arg1, arg2, arg3, arg4, arg5);
}

export function PatchCanvasNode(arg1) {
  return window['go']['main']['App']['PatchCanvasNode'](arg1);
}

export function PickProjectDirectory(arg1) {
  return window['go']['main']['App']['PickProjectDirectory'](arg1);
}

export function ProjectChanges(arg1) {
  return window['go']['main']['App']['ProjectChanges'](arg1);
}

export function ProviderModels(arg1) {
  return window['go']['main']['App']['ProviderModels'](arg1);
}

export function ResumeDialogue(arg1) {
  return window['go']['main']['App']['ResumeDialogue'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function SendTurn(arg1, arg2) {
  return window['go']['main']['App']['SendTurn'](arg1, arg2);
}

export function SetLoop(arg1, arg2) {
  return window['go']['main']['App']['SetLoop'](arg1, arg2);
}

export function SetLoopRunning(arg1, arg2) {
  return window['go']['main']['App']['SetLoopRunning'](arg1, arg2);
}

export function SetModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetModel'](arg1, arg2, arg3);
}

export function SetPipeline(arg1, arg2) {
  return window['go']['main']['App']['SetPipeline'](arg1, arg2);
}

export function SetProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProject'](arg1, arg2, arg3);
}

export function SetRole(arg1, arg2) {
  return window['go']['main']['App']['SetRole'](arg1, arg2);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}

export function StartPipeline(arg1) {
  return window['go']['main']['App']['StartPipeline'](arg1);
}

export function UnlinkNodes(arg1) {
  return window['go']['main']['App']['UnlinkNodes'](arg1);
}

export function UpdateLink(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateLink'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateStatus() {
  return window['go']['main']['App']['UpdateStatus']();
}

export function Usage(arg1) {
  return window['go']['main']['App']['Usage'](arg1);
}
